
/**
Constructor
Do not call Function in Constructor.
*/
class feed_view_1()
{
	super();

	//TODO:edit here

}
extends AView;


function feed_view_1*init(context, evtListener)
{
	super.init(context, evtListener);

	//TODO:edit here

};

function feed_view_1*onInitDone()
{
	super.onInitDone();

	//TODO:edit here

};

function feed_view_1*onActiveDone(isFirst)
{
	super.onActiveDone(isFirst);

	//TODO:edit here

};
