
/**
Constructor
Do not call Function in Constructor.
*/
class feed_sub_view1()
{
	super();

	//TODO:edit here

}
extends AView;


function feed_sub_view1*init(context, evtListener)
{
	super.init(context, evtListener);

	//TODO:edit here

};

function feed_sub_view1*onInitDone()
{
	super.onInitDone();

	//TODO:edit here

};

function feed_sub_view1*onActiveDone(isFirst)
{
	super.onActiveDone(isFirst);

	//TODO:edit here

};
