
/**
Constructor
Do not call Function in Constructor.
*/
class grid_test()
{
	super();

	//TODO:edit here

}
extends AView;


function grid_test*init(context, evtListener)
{
	super.init(context, evtListener);

	//TODO:edit here

};

function grid_test*onInitDone()
{
	super.onInitDone();

	//TODO:edit here

};

function grid_test*onActiveDone(isFirst)
{
	super.onActiveDone(isFirst);

	//TODO:edit here

};
