
/**
Constructor
Do not call Function in Constructor.
*/
class media_tab_view()
{
	super();

	//TODO:edit here

}
extends AView;


function media_tab_view*init(context, evtListener)
{
	super.init(context, evtListener);

	//TODO:edit here

};

function media_tab_view*onInitDone()
{
	super.onInitDone();

	//TODO:edit here

};

function media_tab_view*onActiveDone(isFirst)
{
	super.onActiveDone(isFirst);

	//TODO:edit here

};
