
/**
Constructor
Do not call Function in Constructor.
*/
class news_tab_3()
{
	super();

	//TODO:edit here

}
extends AView;


function news_tab_3*init(context, evtListener)
{
	super.init(context, evtListener);

	//TODO:edit here

};

function news_tab_3*onInitDone()
{
	super.onInitDone();

	//TODO:edit here

};

function news_tab_3*onActiveDone(isFirst)
{
	super.onActiveDone(isFirst);

	//TODO:edit here

};
