
/**
Constructor
Do not call Function in Constructor.
*/
class news_tab_2()
{
	super();

	//TODO:edit here

}
extends AView;


function news_tab_2*init(context, evtListener)
{
	super.init(context, evtListener);

	//TODO:edit here

};

function news_tab_2*onInitDone()
{
	super.onInitDone();

	//TODO:edit here

};

function news_tab_2*onActiveDone(isFirst)
{
	super.onActiveDone(isFirst);

	//TODO:edit here

};
