
/**
Constructor
Do not call Function in Constructor.
*/
class shopping_tab_1()
{
	super();

	//TODO:edit here

}
extends AView;


function shopping_tab_1*init(context, evtListener)
{
	super.init(context, evtListener);

	//TODO:edit here

};

function shopping_tab_1*onInitDone()
{
	super.onInitDone();

	//TODO:edit here

};

function shopping_tab_1*onActiveDone(isFirst)
{
	super.onActiveDone(isFirst);

	//TODO:edit here

};
