
/**
Constructor
Do not call Function in Constructor.
*/
class subview5()
{
	super();

	//TODO:edit here

}
extends AView;


function subview5*init(context, evtListener)
{
	super.init(context, evtListener);

	//TODO:edit here

};

function subview5*onInitDone()
{
	super.onInitDone();

	//TODO:edit here

};

function subview5*onActiveDone(isFirst)
{
	super.onActiveDone(isFirst);

	//TODO:edit here

};
