
/**
Constructor
Do not call Function in Constructor.
*/
class subview2()
{
	super();

	//TODO:edit here

}
extends AView;


function subview2*init(context, evtListener)
{
	super.init(context, evtListener);

	//TODO:edit here

};

function subview2*onInitDone()
{
	super.onInitDone();

	//TODO:edit here

};

function subview2*onActiveDone(isFirst)
{
	super.onActiveDone(isFirst);

	//TODO:edit here

};
