
/**
Constructor
Do not call Function in Constructor.
*/
class subview3()
{
	super();

	//TODO:edit here

}
extends AView;


function subview3*init(context, evtListener)
{
	super.init(context, evtListener);

	//TODO:edit here

};

function subview3*onInitDone()
{
	super.onInitDone();

	//TODO:edit here

};

function subview3*onActiveDone(isFirst)
{
	super.onActiveDone(isFirst);

	//TODO:edit here

};
