
/**
Constructor
Do not call Function in Constructor.
*/
class subview4()
{
	super();

	//TODO:edit here

}
extends AView;


function subview4*init(context, evtListener)
{
	super.init(context, evtListener);

	//TODO:edit here

};

function subview4*onInitDone()
{
	super.onInitDone();

	//TODO:edit here

};

function subview4*onActiveDone(isFirst)
{
	super.onActiveDone(isFirst);

	//TODO:edit here

};
